# fly.toml app configuration file generated for odontoschultz on 2025-11-06T05:17:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'odontoschultz'
primary_region = 'gru'

[build]
  dockerfile = "Dockerfile"

[env]
  N8N_PORT = "5678"
  N8N_PROTOCOL = "https"
  N8N_HOST = "0.0.0.0"
  WEBHOOK_URL = "https://odontoschultz.fly.dev"
  NODE_ENV = "production"
  N8N_RUNNERS_ENABLED = "true"
  EXECUTIONS_MODE = "regular"
  GENERIC_TIMEZONE = "America/Sao_Paulo"
  DB_TYPE = "postgresdb"
  DB_POSTGRESDB_CONNECTION_STRING = "${DATABASE_URL}"
  N8N_PROXY_HOPS = "1"
  N8N_BLOCK_ENV_ACCESS_IN_NODE = "false"
  N8N_GIT_NODE_DISABLE_BARE_REPOS = "true"

[[services]]
  protocol = "tcp"
  internal_port = 5678

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# Volume para persistência dos dados do n8n
[mounts]
  source = "n8n_data"
  destination = "/home/node/.n8n"
  initial_size = "1gb"
